# Generated by Django 3.2.5 on 2021-07-26 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LEbeats', '0002_auto_20210717_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['artist'],
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='LEbeats.artist'),
        ),
    ]
