# Generated by Django 3.2.5 on 2021-07-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEbeats', '0003_auto_20210725_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
