# Generated by Django 3.2.5 on 2021-07-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEbeats', '0004_remove_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),

    ]
