# Generated by Django 3.2.6 on 2021-08-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEbeats', '0005_auto_20210729_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
